# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\DataProvider\OperationCollectionDataProvider:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $tokenStorage: '@security.token_storage'
            $decorated: '@api_platform.doctrine.orm.state.collection_provider'
        tags:
            - { name: 'api_platform.state_provider', priority: 10 }

    App\DataProvider\CategoryCollectionDataProvider:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $tokenStorage: '@security.token_storage'
        tags:
            - { name: 'api_platform.state_provider', priority: 10 }

    App\DataPersister\OperationDataPersister:
        decorates: 'api_platform.doctrine.orm.state.persist_processor'
        arguments:
            $decorated: '@App\DataPersister\OperationDataPersister.inner'
            $security: '@security.helper'
        tags:
            - { name: 'api_platform.state_processor' }

    App\DataPersister\CategoryDataPersister:
        decorates: 'api_platform.doctrine.orm.state.persist_processor'
        arguments:
            $decorated: '@App\DataPersister\CategoryDataPersister.inner'
            $security: '@security.helper'
        tags:
            - { name: 'api_platform.state_processor' }