services:
  backend:
    container_name: back_symfony_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - "8000:80"
    depends_on:
      - database

  database:
    container_name: back_mysql_db
    image: mysql:8.3.0
    ports:
      - "3306:3306" # Port MySQL par défaut
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: project_mybank_db
    volumes:
      - mybank_db_data:/var/lib/mysql

  phpmyadmin:
    container_name: back_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
volumes:
  mybank_db_data:
